<?php

// styles
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
  $parent_style = 'parent-style'; // This is 'twentyfifteen-style' for the Twenty Fifteen theme.

  wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
  wp_enqueue_style( 'child-style',
      get_stylesheet_directory_uri() . '/style.css',
      array( $parent_style ),
      wp_get_theme()->get('Version')
  );

  wp_enqueue_style( 'adobe-fonts', esc_url_raw( 'https://use.typekit.net/zcg5zqr.css' ), array(), null );
  // wp_enqueue_style( 'prismjs-css', esc_url_raw( 'https://cdn.jsdelivr.net/npm/prismjs@1.16.0/themes/prism-twilight.css' ), array(), null );

  // wp_register_script( 'prismjs-js', esc_url_raw( 'https://cdn.jsdelivr.net/npm/prismjs@1.16.0/prism.min.js' ), array(), true );
  // wp_enqueue_script( 'prismjs-js' );
}

// custom widget area (for the header) made for the search bar
function wpb_widgets_init() {

  register_sidebar( array(
      'name'          => 'Custom Header Widget Area',
      'id'            => 'custom-header-widget',
      'before_widget' => '<div class="chw-widget">',
      'after_widget'  => '</div>',
      'before_title'  => '<h2 class="chw-title">',
      'after_title'   => '</h2>',
  ) );

}
add_action( 'widgets_init', 'wpb_widgets_init' );


// swap placeholder text for search bar to "Search the docs (Press "/" as a shortcut)"
function wpforo_search_form( $html ) {
  $html = str_replace( 'placeholder="Search &hellip;"', "placeholder='Search the docs (Press \"/\" as a shortcut)' required", $html );
  return $html;
}
add_filter( 'get_search_form', 'wpforo_search_form' );


// algolia instant search on homepage
add_action( 'wp_enqueue_scripts', function () {
  // Enqueue the instantsearch.js default styles.
  wp_enqueue_style( 'algolia-instantsearch' );
  // Ensure jQuery is loaded.
  wp_enqueue_script( 'jquery' );
  // Enqueue the instantsearch.js library.
  wp_enqueue_script( 'algolia-instantsearch' );
  // WordPress utility useful for using underscore templating.
  wp_enqueue_script( 'wp-util' );
  // Allow users to easily enqueue custom styles and scripts.
  do_action( 'algolia_instantsearch_scripts' );
} );


// default admin dashboard to weDocs page
function dashboard_redirect(){
  wp_redirect(admin_url('admin.php?page=wedocs'));
}
add_action('load-index.php','dashboard_redirect');

function login_redirect( $redirect_to, $request, $user ){
  return admin_url('admin.php?page=wedocs');
}
add_filter('login_redirect','login_redirect',10,3);


// remove top level admin menu items
add_action( 'admin_menu', 'Wps_remove_tools', 99 );
function Wps_remove_tools(){
  remove_menu_page( 'index.php' ); // Dashboard
  remove_menu_page( 'edit.php' ); // Posts
  remove_menu_page( 'link-manager.php' ); // Links
  remove_menu_page( 'edit-comments.php' ); // Comments
  remove_menu_page( 'edit.php?post_type=page' ); // Pages
  remove_menu_page( 'tools.php' ); // Tools
}


// reorder top level admin menu items
function wpse_custom_menu_order( $menu_ord ) {
  if ( !$menu_ord ) return true;

  return array(
      'wedocs', // weDocs
      'separator1', // First separator
      'upload.php', // Media
      'separator2', // Second separator
      'themes.php', // Appearance
      'plugins.php', // Plugins
      'users.php', // Users
      'options-general.php', // Settings
      'separator-last', // Last separator
  );
}
add_filter( 'custom_menu_order', 'wpse_custom_menu_order', 10, 1 );
add_filter( 'menu_order', 'wpse_custom_menu_order', 10, 1 );


// Remove items from the admin bar
function remove_from_admin_bar($wp_admin_bar) {
  /*
    * Placing items in here will only remove them from admin bar
    * when viewing the fronte end of the site
  */
  if ( ! is_admin() ) {
      // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
      // $wp_admin_bar->remove_node('si_menu');

      // WordPress Core Items (uncomment to remove)
      // $wp_admin_bar->remove_node('updates');
      // $wp_admin_bar->remove_node('comments');
      // $wp_admin_bar->remove_node('new-content');
      // $wp_admin_bar->remove_node('wp-logo');
      //$wp_admin_bar->remove_node('site-name');
      //$wp_admin_bar->remove_node('my-account');
      //$wp_admin_bar->remove_node('search');
      // $wp_admin_bar->remove_node('customize');
  }

  /*
    * Items placed outside the if statement will remove it from both the frontend
    * and backend of the site
  */
  $wp_admin_bar->remove_node('comments');
  $wp_admin_bar->remove_node('new-content');
  $wp_admin_bar->remove_node('wp-logo');
  $wp_admin_bar->remove_node('customize');
}
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);